# Generated by Django 4.1.13 on 2025-06-06 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id', models.AutoField(db_column='status_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'статус записи',
                'verbose_name_plural': 'статусы записей',
                'db_table': 'appointment_statuses',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(db_column='clinic_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('address', models.TextField(blank=True, verbose_name='адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='телефон')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('timetable', models.JSONField(blank=True, null=True, verbose_name='расписание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
            ],
            options={
                'verbose_name': 'клиника',
                'verbose_name_plural': 'клиники',
                'db_table': 'clinics',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(db_column='role_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(db_column='service_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='базовая цена')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='длительность, мин')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(db_column='species_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'вид животного',
                'verbose_name_plural': 'виды животных',
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='фамилия')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='телефон')),
                ('password_hash', models.TextField(blank=True, verbose_name='хеш пароля')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('role', models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='vetclinic.role', verbose_name='роль')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(db_column='vet_id', primary_key=True, serialize=False)),
                ('specialization', models.CharField(blank=True, max_length=150, verbose_name='специализация')),
                ('bio', models.TextField(blank=True, verbose_name='биография')),
                ('photo', models.ImageField(blank=True, db_column='photo_path', null=True, upload_to='vets/', verbose_name='фото')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('clinic', models.ForeignKey(db_column='clinic_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vets', to='vetclinic.clinic', verbose_name='клиника')),
            ],
            options={
                'verbose_name': 'ветеринар',
                'verbose_name_plural': 'ветеринары',
                'db_table': 'vets',
            },
        ),
        migrations.CreateModel(
            name='VetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='vetclinic.service', verbose_name='услуга')),
                ('vet', models.ForeignKey(db_column='vet_id', on_delete=django.db.models.deletion.CASCADE, to='vetclinic.vet', verbose_name='ветеринар')),
            ],
            options={
                'verbose_name': 'услуга ветеринара',
                'verbose_name_plural': 'услуги ветеринара',
                'db_table': 'vet_services',
                'unique_together': {('vet', 'service')},
            },
        ),
        migrations.AddField(
            model_name='vet',
            name='services',
            field=models.ManyToManyField(related_name='vets', through='vetclinic.VetService', to='vetclinic.service', verbose_name='оказываемые услуги'),
        ),
        migrations.AddField(
            model_name='vet',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='veterinary_profiles', to='vetclinic.user', verbose_name='пользователь'),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(db_column='pet_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='кличка')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='порода')),
                ('gender', models.CharField(choices=[('M', 'М'), ('F', 'Ж')], max_length=1, verbose_name='пол')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='вес (кг)')),
                ('photo', models.ImageField(blank=True, db_column='photo_path', null=True, upload_to='pets/', verbose_name='фото')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('owner', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='vetclinic.user', verbose_name='владелец')),
                ('species', models.ForeignKey(db_column='species_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='vetclinic.species', verbose_name='вид')),
            ],
            options={
                'verbose_name': 'питомец',
                'verbose_name_plural': 'питомцы',
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(db_column='appointment_id', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='конец')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('clinic', models.ForeignKey(db_column='clinic_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vetclinic.clinic', verbose_name='клиника')),
                ('created_by_user', models.ForeignKey(db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vetclinic.user', verbose_name='создал')),
                ('pet', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vetclinic.pet', verbose_name='питомец')),
                ('service', models.ForeignKey(db_column='service_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vetclinic.service', verbose_name='услуга')),
                ('status', models.ForeignKey(db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vetclinic.appointmentstatus', verbose_name='статус')),
                ('updated_by_user', models.ForeignKey(db_column='updated_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vetclinic.user', verbose_name='обновил')),
                ('vet', models.ForeignKey(db_column='vet_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vetclinic.vet', verbose_name='ветеринар')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
                'db_table': 'appointments',
            },
        ),
    ]
